version: 2

networks:
  primary:
    external:
      name: primary
  website_net:
    external: false

services:
  website:
    image: registry.nush.app/appventure-website-v3:latest
    container_name: appventure-website
    restart: always
    networks:
      - primary
      - website_net
    environment:
      - API_URL=http://strapi:8081
      - HOST=website
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.website.rule=Host(`nush.app`)"
    - "traefik.http.routers.website.entryPoints=https"
    - "traefik.http.routers.website.tls=true"
    - "traefik.http.routers.website.tls.certresolver=tlsresolver"
    - "traefik.http.middlewares.bustimings-redirect-regex.redirectregex.regex=^https://nush.app/bustimings"
    - "traefik.http.middlewares.bustimings-redirect-regex.redirectregex.replacement=https://bustimings.nush.app"
    - "traefik.http.middlewares.bustimings-redirect-regex.redirectregex.permanent=true"
    - "traefik.http.routers.website.middlewares=bustimings-redirect-regex"
  strapi:
    container_name: strapi
    image: registry.nush.app/appventure-api-v3:latest
    environment:
      - PORT=8081
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    volumes:
      - ./app:/srv/app
    depends_on:
      - db
    networks:
     - primary
     - website_net
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.api.rule=Host(`nush.app`) && PathPrefix(`/api`) || PathPrefix(`/admin`)"
    - "traefik.http.routers.api.entryPoints=https"
    - "traefik.http.routers.api.tls=true"
    - "traefik.http.routers.api.tls.certresolver=tlsresolver"
  db:
    container_name: mysql
    image: mysql
    restart: always
    networks:
    - website_net
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - ./db:/var/lib/mysql
