version: 2

networks:
  primary:
    external:
      name: primary
  website_net:
    external: false

services:
  website:
      image: appventure.nushigh.edu.sg/appventure-website-v3:master
      build: .
      container_name: appventure-website
      restart: always
      networks:
      - primary
      - website_net
      environment:
      - API_URL=http://localhost:8080
      - HOST=0.0.0.0
      labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:appventure.nushigh.edu.sg"
      - "traefik.frontend.entryPoints=https"
      - "traefik.port=8080"
      - "traefik.docker.network=primary"

  strapi:
    container_name: strapi
    image: appventure.nushigh.edu.sg/appventure-api-v3:master
    build: .
    environment:
      - PORT=8080
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=0.0.0.0
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    volumes:
      - ./app:/srv/app
    depends_on:
      - db
    networks:
    - primary
    - website_net
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:appventure.nushigh.edu.sg;PathPrefix:/api,/admin,/users-permissions,/settings-manager,/content-type-builder"
    - "traefik.frontend.entryPoints=https"
    - "traefik.port=8080"
    - "traefik.docker.network=primary"

  db:
    container_name: mysql
    image: mysql
    restart: always
    networks:
    - website_net
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - ./db:/var/lib/mysql
